import type { Application } from "./types";

// Note: These mocks use string IDs cast to Convex Id types for development/testing
// In production, real Convex IDs would be used
export const MOCK_APPLICATIONS = [
  {
    _id: "app_001",
    applicationCode: "APP-2026-001",
    status: "pending",
    userId: "user_client_123",
    organizationSlug: "acme-sports",
    createdAt: "2026-01-13T10:30:00Z",
    updatedAt: "2026-01-13T10:30:00Z",
    format: "full-time",
    program: "basketball",
    enrollmentYear: "2026",
    graduationYear: "2030",
    firstName: "Juan",
    lastName: "Pérez",
    sex: "male",
    height: "6'2\"",
    birthDate: "2008-05-15",
    email: "juan.perez@example.com",
    telephone: "+1234567890",
    countryOfBirth: "Mexico",
    countryOfCitizenship: "Mexico",
    highlightsLink: "https://youtube.com/watch?v=example1",
    gradeEntering: "11th",
    programOfInterest: "Basketball Academy",
    needsI20: "yes",
    country: "USA",
    state: "California",
    city: "Los Angeles",
    streetAddress: "123 Main St",
    zipCode: "90001",
    currentSchoolName: "Lincoln High School",
    currentSchoolType: "public",
    currentGPA: "3.8",
    schoolAddress: "456 School Ave",
    schoolCity: "Los Angeles",
    schoolCountry: "USA",
    schoolState: "California",
    schoolZipCode: "90002",
    referenceFullName: "Coach Mike Johnson",
    referencePhone: "+1234567891",
    referenceRelationship: "Basketball Coach",
    parent1FirstName: "Carlos",
    parent1LastName: "Pérez",
    parent1Relationship: "Father",
    parent1Email: "carlos.perez@example.com",
    parent1Telephone: "+1234567892",
    parent2FirstName: "María",
    parent2LastName: "García",
    parent2Relationship: "Mother",
    parent2Email: "maria.garcia@example.com",
    parent2Telephone: "+1234567893",
    personSubmitting: "parent",
    howDidYouHear: "socialMedia",
    interestedInBoarding: "yes",
    message:
      "My son is very passionate about basketball and dreams of playing professionally.",
  },
  {
    _id: "app_002",
    applicationCode: "APP-2026-002",
    status: "approved",
    userId: "user_client_456",
    organizationSlug: "acme-sports",
    createdAt: "2026-01-12T14:20:00Z",
    updatedAt: "2026-01-13T09:00:00Z",
    format: "part-time",
    program: "soccer",
    enrollmentYear: "2026",
    graduationYear: "2029",
    firstName: "María",
    lastName: "González",
    sex: "female",
    height: "5'6\"",
    birthDate: "2009-08-22",
    email: "maria.gonzalez@example.com",
    telephone: "+1234567894",
    countryOfBirth: "Colombia",
    countryOfCitizenship: "Colombia",
    highlightsLink: "https://youtube.com/watch?v=example2",
    gradeEntering: "10th",
    programOfInterest: "Soccer Development",
    needsI20: "no",
    country: "USA",
    state: "Florida",
    city: "Miami",
    streetAddress: "789 Ocean Drive",
    zipCode: "33101",
    currentSchoolName: "Miami Central High",
    currentSchoolType: "public",
    currentGPA: "3.9",
    schoolAddress: "321 Education Blvd",
    schoolCity: "Miami",
    schoolCountry: "USA",
    schoolState: "Florida",
    schoolZipCode: "33102",
    referenceFullName: "Coach Sarah Williams",
    referencePhone: "+1234567895",
    referenceRelationship: "Soccer Coach",
    parent1FirstName: "Jorge",
    parent1LastName: "González",
    parent1Relationship: "Father",
    parent1Email: "jorge.gonzalez@example.com",
    parent1Telephone: "+1234567896",
    parent2FirstName: "Ana",
    parent2LastName: "Rodríguez",
    parent2Relationship: "Mother",
    parent2Email: "ana.rodriguez@example.com",
    parent2Telephone: "+1234567897",
    personSubmitting: "self",
    howDidYouHear: "friend",
    interestedInBoarding: "no",
    message:
      "I have been playing soccer since I was 5 and want to take my skills to the next level.",
  },
  {
    _id: "app_003",
    applicationCode: "APP-2026-003",
    status: "rejected",
    userId: "user_client_123",
    organizationSlug: "acme-sports",
    createdAt: "2026-01-11T08:45:00Z",
    updatedAt: "2026-01-12T16:30:00Z",
    format: "full-time",
    program: "volleyball",
    enrollmentYear: "2025",
    graduationYear: "2029",
    firstName: "Juan",
    lastName: "Pérez",
    sex: "male",
    height: "6'4\"",
    birthDate: "2008-05-15",
    email: "juan.perez@example.com",
    telephone: "+1234567890",
    countryOfBirth: "Mexico",
    countryOfCitizenship: "Mexico",
    highlightsLink: "https://youtube.com/watch?v=example3",
    gradeEntering: "11th",
    programOfInterest: "Volleyball Training",
    needsI20: "yes",
    country: "USA",
    state: "California",
    city: "Los Angeles",
    streetAddress: "123 Main St",
    zipCode: "90001",
    currentSchoolName: "Lincoln High School",
    currentSchoolType: "public",
    currentGPA: "3.8",
    schoolAddress: "456 School Ave",
    schoolCity: "Los Angeles",
    schoolCountry: "USA",
    schoolState: "California",
    schoolZipCode: "90002",
    referenceFullName: "Coach Mike Johnson",
    referencePhone: "+1234567891",
    referenceRelationship: "Volleyball Coach",
    parent1FirstName: "Carlos",
    parent1LastName: "Pérez",
    parent1Relationship: "Father",
    parent1Email: "carlos.perez@example.com",
    parent1Telephone: "+1234567892",
    parent2FirstName: "María",
    parent2LastName: "García",
    parent2Relationship: "Mother",
    parent2Email: "maria.garcia@example.com",
    parent2Telephone: "+1234567893",
    personSubmitting: "parent",
    howDidYouHear: "coach",
    interestedInBoarding: "yes",
    message: "Application incomplete - missing required documents.",
  },
  {
    _id: "app_004",
    applicationCode: "APP-2026-004",
    status: "under_review",
    userId: "user_client_789",
    organizationSlug: "acme-sports",
    createdAt: "2026-01-13T11:15:00Z",
    updatedAt: "2026-01-13T11:15:00Z",
    format: "full-time",
    program: "basketball",
    enrollmentYear: "2026",
    graduationYear: "2030",
    firstName: "Carlos",
    lastName: "Rodríguez",
    sex: "male",
    height: "6'0\"",
    birthDate: "2008-11-03",
    email: "carlos.rodriguez@example.com",
    telephone: "+1234567898",
    countryOfBirth: "Puerto Rico",
    countryOfCitizenship: "Puerto Rico",
    highlightsLink: "https://youtube.com/watch?v=example4",
    gradeEntering: "11th",
    programOfInterest: "Basketball Elite Program",
    needsI20: "no",
    country: "USA",
    state: "New York",
    city: "New York",
    streetAddress: "456 Broadway",
    zipCode: "10001",
    currentSchoolName: "Brooklyn Tech High School",
    currentSchoolType: "public",
    currentGPA: "4.0",
    schoolAddress: "789 Tech Ave",
    schoolCity: "Brooklyn",
    schoolCountry: "USA",
    schoolState: "New York",
    schoolZipCode: "11201",
    referenceFullName: "Coach David Martinez",
    referencePhone: "+1234567899",
    referenceRelationship: "Head Coach",
    parent1FirstName: "Roberto",
    parent1LastName: "Rodríguez",
    parent1Relationship: "Father",
    parent1Email: "roberto.rodriguez@example.com",
    parent1Telephone: "+1234567900",
    parent2FirstName: "Isabel",
    parent2LastName: "Torres",
    parent2Relationship: "Mother",
    parent2Email: "isabel.torres@example.com",
    parent2Telephone: "+1234567901",
    personSubmitting: "coach",
    howDidYouHear: "teacher",
    interestedInBoarding: "yes",
    message: "Outstanding student-athlete with leadership qualities.",
  },
];

export const CURRENT_USER_ID = "user_client_123";
export const IS_ADMIN = true;

export function getApplicationsByRole(isAdmin: boolean, userId: string) {
  if (isAdmin) {
    return MOCK_APPLICATIONS;
  }
  return MOCK_APPLICATIONS.filter((app) => app.userId === userId);
}
